/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.motors.horizon.view;

import com.motors.horizon.model.dao.UsuarioDao;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author 823214424
 */
public class CadastroHorizonMotors extends javax.swing.JFrame {

    /**
     * Creates new form CadastroHorizonMotors
     */
    public CadastroHorizonMotors() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelAviso = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextEmail = new javax.swing.JTextPane();
        jLabelSenha = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jLabelConSenha = new javax.swing.JLabel();
        jConfirmPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        botaoCadastroTelaCadastro = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        botaoEntre = new javax.swing.JToggleButton();
        jLabelTel = new javax.swing.JLabel();
        jScrollNome = new javax.swing.JScrollPane();
        jTextNome = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextCpf = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextTel = new javax.swing.JTextPane();
        jLabelCpf = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(802, 459));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAviso.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelAviso.setText("Faça seu cadastro");
        jPanel1.add(jLabelAviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabelNome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelNome.setText("Nome *");
        jPanel1.add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelEmail.setText("Email *");
        jPanel1.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jTextEmail.setBackground(new java.awt.Color(204, 204, 204));
        jTextEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane2.setViewportView(jTextEmail);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 146, -1));

        jLabelSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelSenha.setText("Senha *");
        jPanel1.add(jLabelSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jPassword.setBackground(new java.awt.Color(204, 204, 204));
        jPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 146, -1));

        jLabelConSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelConSenha.setText("Confirme a sua senha *");
        jPanel1.add(jLabelConSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jConfirmPassword.setBackground(new java.awt.Color(204, 204, 204));
        jConfirmPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConfirmPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 146, -1));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 156, -1, -1));

        botaoCadastroTelaCadastro.setBackground(new java.awt.Color(51, 255, 204));
        botaoCadastroTelaCadastro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        botaoCadastroTelaCadastro.setForeground(new java.awt.Color(255, 255, 255));
        botaoCadastroTelaCadastro.setText("Cadastre-se");
        botaoCadastroTelaCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.W_RESIZE_CURSOR));
        botaoCadastroTelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroTelaCadastroActionPerformed(evt);
            }
        });
        jPanel1.add(botaoCadastroTelaCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, 36));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel11.setText("Já possui uma conta?");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, 10));

        botaoEntre.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        botaoEntre.setForeground(new java.awt.Color(51, 255, 204));
        botaoEntre.setText("Entre");
        botaoEntre.setBorder(null);
        botaoEntre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEntreActionPerformed(evt);
            }
        });
        jPanel1.add(botaoEntre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, 10));

        jLabelTel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelTel.setText("Telefone*");
        jPanel1.add(jLabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jTextNome.setBackground(new java.awt.Color(204, 204, 204));
        jTextNome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollNome.setViewportView(jTextNome);

        jPanel1.add(jScrollNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 146, -1));

        jTextCpf.setBackground(new java.awt.Color(204, 204, 204));
        jTextCpf.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane6.setViewportView(jTextCpf);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 146, -1));

        jTextTel.setBackground(new java.awt.Color(204, 204, 204));
        jTextTel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane7.setViewportView(jTextTel);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 146, -1));

        jLabelCpf.setText("CPF*");
        jPanel1.add(jLabelCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 400, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/motors/horizon/images/hm.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, 465));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed

    }//GEN-LAST:event_jPasswordActionPerformed

    public boolean oneChar(String pass) {
        for (int i = 0; i < pass.length(); i++) {
            if (Character.isLowerCase(pass.charAt(i))) {
                return true;
            }
        }

        return false;
    }

    public boolean oneNumber(String pass) {
        for (int i = 0; i < pass.length(); i++) {
            if (Character.isDigit(pass.charAt(i))) {
                return true;
            }
        }

        return false;
    }

    public boolean noChar(String input) {
        for (int i = 0; i < input.length(); i++) {
            if (!Character.isDigit(input.charAt(i))) {
                return true;
            }
        }
        return false;
    }

    public boolean checkEmail(String input) {
        for (int i = 0; i < input.length(); i++) {
            if (input.charAt(i) == '@') {
                return false;
            }
        }
        return true;
    }

    private void jConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConfirmPasswordActionPerformed

    }//GEN-LAST:event_jConfirmPasswordActionPerformed

    private void botaoCadastroTelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroTelaCadastroActionPerformed
        String nome = jTextNome.getText();
        String cpf = jTextCpf.getText();
        String email = jTextEmail.getText();
        String tel = jTextTel.getText();

        if ("".equals(nome) || "".equals(cpf) || "".equals(email) || "".equals(tel)) {
            jLabelAviso.setText("Preencha todos os campos");
            jLabelAviso.setForeground(Color.red);
        } else if (cpf.length() > 11 && cpf.length() < 11 || noChar(cpf)) {
            jLabelCpf.setText("11 números*");
            jLabelCpf.setForeground(Color.red);
        } else if (checkEmail(email)) {
            jLabelEmail.setText("Email inválido*");
            jLabelEmail.setForeground(Color.red);
        } else if (tel.length() > 11 && tel.length() < 11 || noChar(tel)) {
            jLabelTel.setText("11 números*");
            jLabelTel.setForeground(Color.red);
        } else {
            String pass = jPassword.getText();
            if (!"".equals(pass) && pass.length() >= 8 && oneChar(pass) && oneNumber(pass)) {
                String confirmPass = jConfirmPassword.getText();

                if (pass.equals(confirmPass)) {
                    UsuarioDao user = new UsuarioDao();

                    if (user.checkLogin(cpf)) {
                        JOptionPane.showMessageDialog(null, "Usuário já cadastrado!");
                    } else {
                        try {
                            user.createUsuario(jTextNome.getText(), jPassword.getText(), jTextEmail.getText(), jTextCpf.getText(), jTextTel.getText());
                        } catch (Exception e) {
                            throw new RuntimeException("Erro na conexão: ", e);
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "As duas senhas precisam ser iguais!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "A senha precisa ter pelo menos:\n- 8 digitos\nUma letra maiúscula\nUm número");
                jPassword.setText("");
            }

        }
    }//GEN-LAST:event_botaoCadastroTelaCadastroActionPerformed

    private void botaoEntreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEntreActionPerformed
        LoginHorizonMotors telaDeLogin = new LoginHorizonMotors();
        CadastroHorizonMotors cad = new CadastroHorizonMotors();
        telaDeLogin.setVisible(true);
        cad.setVisible(false);
    }//GEN-LAST:event_botaoEntreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroHorizonMotors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroHorizonMotors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroHorizonMotors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroHorizonMotors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroHorizonMotors().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoCadastroTelaCadastro;
    private javax.swing.JToggleButton botaoEntre;
    private javax.swing.JPasswordField jConfirmPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAviso;
    private javax.swing.JLabel jLabelConSenha;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JScrollPane jScrollNome;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextPane jTextCpf;
    private javax.swing.JTextPane jTextEmail;
    private javax.swing.JTextPane jTextNome;
    private javax.swing.JTextPane jTextTel;
    // End of variables declaration//GEN-END:variables
}
